// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbwu1POCyCXkNfFjQhLhg0m1UpkvgP6LM',
    appId: '1:35735645622:web:0c8bb1b481626eeea56517',
    messagingSenderId: '35735645622',
    projectId: 'gym-saas-b2851',
    authDomain: 'gym-saas-b2851.firebaseapp.com',
    storageBucket: 'gym-saas-b2851.firebasestorage.app',
    measurementId: 'G-46S3KYFLNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjbbsNO3ROSGKkZIw6KunoftKRYjIXqow',
    appId: '1:35735645622:android:7087b76925295ca1a56517',
    messagingSenderId: '35735645622',
    projectId: 'gym-saas-b2851',
    storageBucket: 'gym-saas-b2851.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0QBv7PVuM40CkmuVbqJO6PjoCOM7p4Kc',
    appId: '1:35735645622:ios:9621d3399f229dd5a56517',
    messagingSenderId: '35735645622',
    projectId: 'gym-saas-b2851',
    storageBucket: 'gym-saas-b2851.firebasestorage.app',
    iosBundleId: 'com.example.saas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0QBv7PVuM40CkmuVbqJO6PjoCOM7p4Kc',
    appId: '1:35735645622:ios:9621d3399f229dd5a56517',
    messagingSenderId: '35735645622',
    projectId: 'gym-saas-b2851',
    storageBucket: 'gym-saas-b2851.firebasestorage.app',
    iosBundleId: 'com.example.saas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbwu1POCyCXkNfFjQhLhg0m1UpkvgP6LM',
    appId: '1:35735645622:web:fbf2a6b3a7f2c403a56517',
    messagingSenderId: '35735645622',
    projectId: 'gym-saas-b2851',
    authDomain: 'gym-saas-b2851.firebaseapp.com',
    storageBucket: 'gym-saas-b2851.firebasestorage.app',
    measurementId: 'G-9R9KLYHB3V',
  );
}
